app/main/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, current_app
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
import os
from .forms import UploadForm
from app.models import Image as DBImage, Diagnosis, DiseaseInfo, db, Feedback
from app.utils import *
from PIL import Image as PILImage  # Use an alias for PIL's Image module



main = Blueprint('main', __name__)

@main.route("/")
def index():
    return render_template('index.html')


@main.route("/history")
@login_required
def history():
    # Define the number of results per page
    per_page = 10
    # Get the page number from the request; default to 1 if not provided
    page = request.args.get('page', 1, type=int)
    # Query the diagnosis history for the current user, ordered by date
    diagnoses_query = Diagnosis.query.filter_by(user_id=current_user.id).order_by(Diagnosis.diagnosis_date.desc())
    diagnoses = diagnoses_query.paginate(page=page, per_page=per_page, error_out=False)
    # Pass the paginated results to the template
    return render_template('history.html', diagnoses=diagnoses)


@main.route("/view_diagnosis/<int:diagnosis_id>")
@login_required
def view_diagnosis(diagnosis_id):
    diagnosis = Diagnosis.query.get_or_404(diagnosis_id)
    
    # Ensure the diagnosis belongs to the current user
    if diagnosis.user_id != current_user.id:
        return redirect(url_for('main.history'))
    
    return render_template('view_diagnosis.html', diagnosis=diagnosis)


@main.route("/upload", methods=['GET', 'POST'])
@login_required
def upload_image():
    form = UploadForm()
    if form.validate_on_submit():
        if form.image.data:
            image_file = secure_filename(form.image.data.filename)
            image_path = os.path.join(current_app.root_path, 'static/uploads', image_file)
            form.image.data.save(image_path)

            # Perform the first classification
            diagnosis_result, confidence_score = classify_health(image_path)

            if diagnosis_result == 'Healthy':
                diagnosis_results = {
                    'diagnosis': 'Healthy',
                    'image_file': image_file
                }
                disease_info_id = None
                disease_confidence_score = 0.0
                disease_name = " "
            else:
                # Perform the second classification if diseased
                disease_name, disease_confidence_score = classify_disease(image_path)

                # Fetch details of the disease from the database
                disease_info = DiseaseInfo.query.filter_by(name=disease_name).first()
                
                if disease_info:
                    diagnosis_results = {
                        'diagnosis': 'Diseased',
                        'disease_name': disease_info.name,
                        'description': disease_info.description,
                        'causes': disease_info.causes,
                        'solutions': disease_info.recommendation_text,
                        'recommendations': disease_info.recommendation_text,
                        'image_file': image_file
                    }
                    disease_info_id = disease_info.id
                else:
                    diagnosis_results = {
                        'diagnosis': 'Diseased',
                        'disease_name': disease_name,
                        'description': 'Details not found',
                        'causes': 'Details not found',
                        'solutions': 'Details not found',
                        'recommendations': 'Details not found',
                        'image_file': image_file
                    }
                    disease_info_id = None

            # Save the image entry to the database
            new_image = DBImage(user_id=current_user.id, image_path=image_path)
            db.session.add(new_image)
            db.session.commit()

            # Save the diagnosis to the database
            diagnosis_entry = Diagnosis(
                image_id=new_image.id,  # Use the ID of the saved image
                disease_info_id=disease_info_id,
                diagnosis=diagnosis_results['diagnosis'],
                confidence_score=disease_confidence_score if diagnosis_results['diagnosis'] == 'Diseased' else confidence_score,
                user_id=current_user.id
            )
            db.session.add(diagnosis_entry)
            db.session.commit()
            
            diagnosis_results['diagnosis_id'] = diagnosis_entry.id
            
            return redirect(url_for('main.results', **diagnosis_results))
    return render_template('uploads.html', title='Upload Image', form=form)



@main.route("/results")
def results():
    diagnosis = request.args.get('diagnosis')
    image_file = request.args.get('image_file')
    diagnosis_id = request.args.get('diagnosis_id')

    if diagnosis == 'Diseased':
        disease_name = request.args.get('disease_name')
        description = request.args.get('description')
        causes = request.args.get('causes')
        solutions = request.args.get('solutions')
        recommendations = request.args.get('recommendations')
        return render_template('results.html', diagnosis=diagnosis, disease_name=disease_name, 
                               description=description, causes=causes, solutions=solutions, 
                               recommendations=recommendations, image_file=image_file,
                               diagnosis_id=diagnosis_id)
    return render_template('results.html', diagnosis=diagnosis, image_file=image_file,
                           diagnosis_id=diagnosis_id)


@main.route('/submit_feedback/<int:diagnosis_id>', methods=['POST'])
def submit_feedback(diagnosis_id):
    accuracy_feedback = request.form.get('accuracy_feedback')
    recommendation_feedback = request.form.get('recommendation_feedback')
    
    feedback = Feedback(
        diagnosis_id=diagnosis_id,
        accuracy_feedback=accuracy_feedback,
        recommendation_feedback=recommendation_feedback
    )
    
    db.session.add(feedback)
    db.session.commit()
    
    flash('Thank you for your feedback!', 'success')
    return redirect(url_for('main.results', diagnosis_id=diagnosis_id))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Lettuce Guardian{% endblock %}</title>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- Custom styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='fav.png') }}" type="image/x-icon">
    <!-- React JS and Babel CDN -->
    <script src="https://unpkg.com/react/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom/umd/react-dom.development.js" crossorigin></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Lettuce Guardian</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    {% if request.endpoint != 'main.index' %}
                        <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                    {% endif %}
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        {% if request.endpoint != 'main.history' %}
                            <a class="nav-link" href="{{ url_for('main.history') }}">History</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if request.endpoint != 'main.upload_image' %}
                            <a class="nav-link" href="{{ url_for('main.upload_image') }}">Upload an Image of Lettuce</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        {% if request.endpoint != 'auth.login' %}
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if request.endpoint != 'auth.register' %}
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        {% endif %}
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    
    <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {% block content %}
        <div id="react-root"></div>
        {% endblock %}
    </div>

    {% block footer %}
   <!-- Footer -->
    <footer class="footer">
        <div class="container text-center">
            <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
        </div>
    </footer>
    {% endblock footer %}
    
    <!-- Bootstrap JS, Popper.js, and jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha384-ZvpUoO/+PpJ6T3FxF8+T6+5M5r7s/8Yl4IvOnE3B/J1cMe5HV/77wBsK8mcEF6i4"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"
            integrity="sha384-Rc9Tpea21n4VZefN6LOOXbRg/uB8vo+HkcQx9ohcZ2l3AtW5xdq5+JVoJv2Gr9z/"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+jFuR0fF0jPxJw+3vqkEc8JOgYb8qU2r0n1"
            crossorigin="anonymous"></script>
    
    <!-- In your base.html, add these scripts in the <head> or before the closing </body> tag -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">


    <!-- Custom JavaScript -->
    <script src="{{ url_for('static', filename='script.js') }}"></script>
<!-- jQuery, Popper.js, and Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

   
</body>
</html>

app/templates/dashboard.html
<!-- app/templates/dashboard.html -->
{% extends "base.html" %}
{% block content %}
    <h1>Welcome to your dashboard, {{ current_user.username }}! 🧑</h1>
    <div class="card">
        <div class="card-header">
        </div>
        
    </div>
{% endblock %}
{% block footer %}
<!-- Footer -->
 <footer class="footer myfoot">
     <div class="container text-center">
         <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
     </div>
 </footer>
 {% endblock footer %}

app/templates/history.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="card mx-auto" style="max-width: 800px;">
        <div class="card-header">
            <h2>Diagnosis History</h2>
        </div>
        <div class="card-body">
            {% if diagnoses.items %}
                <div class="row">
                    {% for diagnosis in diagnoses.items %}
                        <div class="col-md-6 mb-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Diagnosis Date: {{ diagnosis.diagnosis_date.strftime('%Y-%m-%d %H:%M:%S') }}</h5>
                                    <p class="card-text"><strong>Diagnosis:</strong> {{ diagnosis.diagnosis }}</p>
                                    <p class="card-text"><strong>Disease Name:</strong> {{ diagnosis.disease_info.name if diagnosis.disease_info else 'N/A' }}</p>
                                    <a href="{{ url_for('main.view_diagnosis', diagnosis_id=diagnosis.id) }}" class="btn btn-info btn-sm">View Details</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <!-- Pagination Controls -->
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if diagnoses.has_prev %}
                            <li class="page-item">
                                <a class="page-link" href="{{ url_for('main.history', page=diagnoses.prev_num) }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">&laquo;</span>
                            </li>
                        {% endif %}

                        {% for page_num in range(1, diagnoses.pages + 1) %}
                            <li class="page-item {% if page_num == diagnoses.page %}active{% endif %}">
                                <a class="page-link" href="{{ url_for('main.history', page=page_num) }}">{{ page_num }}</a>
                            </li>
                        {% endfor %}

                        {% if diagnoses.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="{{ url_for('main.history', page=diagnoses.next_num) }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">&raquo;</span>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% else %}
                <p>No diagnosis history available.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
<!-- Footer -->
<footer class="footer myfootreset">
    <div class="container text-center">
        <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
    </div>
</footer>
{% endblock footer %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="container form-container mt-5">
        <div class="card">
            <div class="card-header">
                <h2>Login</h2>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ url_for('auth.login') }}">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.email.label }} {{ form.email(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.password.label }} {{ form.password(class="form-control") }}
                    </div>
                    <div class="form-group form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                    <div class="text-center mt-3">
                        <a href="{{ url_for('auth.reset_request') }}">Forgot Password?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
<!-- Footer -->
 <footer class="footer myfootlog">
     <div class="container text-center">
         <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
     </div>
 </footer>
 {% endblock footer %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
    <div class="container form-container mt-5">
        <div class="card">
            <div class="card-header">
                <h2>Register</h2>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ url_for('auth.register') }}">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.username.label }} {{ form.username(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.email.label }} {{ form.email(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.password.label }} {{ form.password(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.confirm_password.label }} {{ form.confirm_password(class="form-control") }}
                    </div>
                    <button type="submit" class="btn btn-primary">Sign Up</button>
                    <div class="text-center mt-3">
                        <p>Already have an account? <a href="{{ url_for('auth.login') }}">Login</a></p>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
<!-- Footer -->
 <footer class="footer myfootlog">
     <div class="container text-center">
         <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
     </div>
 </footer>
 {% endblock footer %}

app/templates/reset_request.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header text-center">
                        <h2>Reset Password</h2>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {{ form.hidden_tag() }}
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}
                                {{ form.email(class="form-control form-width") }}
                                {% for error in form.email.errors %}
                                    <div class="text-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Request Password Reset</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
<!-- Footer -->
 <footer class="footer myfootreset">
     <div class="container text-center">
         <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
     </div>
 </footer>
 {% endblock footer %}

app/templates/reset_token.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}

{% block content %}
    <h1 class="text-center">Reset Password</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control") }}
            {% for error in form.password.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {{ form.confirm_password(class="form-control") }}
            {% for error in form.confirm_password.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary btn-block">Reset Password</button>
    </form>
{% endblock %}


{% block footer %}
<!-- Footer -->
 <footer class="footer myfootreset">
     <div class="container text-center">
         <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
     </div>
 </footer>
 {% endblock footer %}

app/templates/results.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="card mx-auto" style="max-width: 800px;">
        <div class="card-header bg-primary text-white">
            <h2>Diagnosis Results</h2>
        </div>
        <div class="card-body">
            <img src="{{ url_for('static', filename='uploads/' ~ image_file) }}" style="width: auto; height: 500px;" alt="Uploaded Image" class="img-fluid mb-4 rounded mx-auto d-block">
            <h4 class="card-title">Diagnosis: {{ diagnosis }}</h4>
            {% if diagnosis != 'Healthy' %}
            <div class="card mb-3">
                <div class="card-body">
                    <p><strong>Disease Name:</strong> {{ disease_name }}</p>
                    <p><strong>Description:</strong> {{ description }}</p>
                    <p><strong>Causes:</strong> {{ causes }}</p>
                    <p><strong>Solutions:</strong> {{ solutions }}</p>
                    <p><strong>Recommendations:</strong> {{ recommendations }}</p>
                </div>
            </div>
            {% else %}
            <div class="alert alert-success" role="alert">
                Your lettuce plant appears to be healthy!
            </div>
            {% endif %}
            <a href="{{ url_for('main.upload_image') }}" class="btn btn-primary mt-3">Upload Another Image</a>

            <div class="mt-5">
                <h2>Provide Feedback (Optional)</h2>
                <form action="{{ url_for('main.submit_feedback', diagnosis_id=diagnosis_id) }}" method="POST">
                    <div class="form-group">
                        <label for="accuracy_feedback">How accurate was the diagnosis?</label>
                        <input type="text" id="accuracy_feedback" name="accuracy_feedback" class="form-control" placeholder="e.g., Very accurate">
                    </div>
                    <div class="form-group">
                        <label for="recommendation_feedback">How effective were the recommendations?</label>
                        <input type="text" id="recommendation_feedback" name="recommendation_feedback" class="form-control" placeholder="e.g., Very effective">
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Submit Feedback</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
<!-- Footer -->
<footer class="footer myfootlog bg-dark text-white py-3">
    <div class="container text-center">
        <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
    </div>
</footer>
{% endblock %}

app/templates/uploads.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="card mx-auto" style="max-width: 500px;">
        <div class="card-header">
            <h2>Upload Lettuce Image</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ url_for('main.upload_image') }}" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.image.label }} {{ form.image(class="form-control-file") }}
                </div>
                <button type="submit" class="btn btn-primary mt-3">Upload</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
<!-- Footer -->
 <footer class="footer myfootreset">
     <div class="container text-center">
         <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
     </div>
 </footer>
 {% endblock footer %}

app/templates/view_diagnosis.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="card mx-auto" style="max-width: 800px;">
        <div class="card-header">
            <h2>Diagnosis Details</h2>
        </div>
        <div class="card-body">
            <img src="{{ url_for('static', filename='uploads/' ~ image_file) }}" alt="Uploaded Image" class="img-fluid mb-4">
            <h4>Date: {{ diagnosis.diagnosis_date.strftime('%Y-%m-%d %H:%M:%S') }}</h4>
            <h4>Diagnosis: {{ diagnosis.diagnosis }}</h4>
            {% if diagnosis.diagnosis == 'Diseased' %}
                <p><strong>Disease Name:</strong> {{ diagnosis.disease_info.name }}</p>
                <p><strong>Description:</strong> {{ diagnosis.disease_info.description }}</p>
                <p><strong>Causes:</strong> {{ diagnosis.disease_info.causes }}</p>
                <p><strong>Solutions:</strong> {{ diagnosis.disease_info.recommendation_text }}</p>
                <p><strong>Recommendations:</strong> {{ diagnosis.disease_info.recommendation_text }}</p>
            {% else %}
                <p>Your lettuce plant appeared to be healthy.</p>
            {% endif %}
            <a href="{{ url_for('main.history') }}" class="btn btn-primary mt-3">Back to History</a>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
<!-- Footer -->
 <footer class="footer myfootlog">
     <div class="container text-center">
         <p class="mb-0">© 2024 Lettuce Guardian. All rights reserved.</p>
     </div>
 </footer>
 {% endblock footer %}